Fix wrong .env key name in README
If you use the key specified in the docs as-is, you get an error:

Error: This function requires a clientId

This is because the code reads the values:
clientId: process.env.NYLAS_CLIENT_ID,
clientSecret: process.env.NYLAS_CLIENT_SECRET,

But the README calls it:
CLIENT_ID=client_id...
CLIENT_SECRET=client_secret...

So I changed the README to reflect this :)